__all__ = ["Endpoints"]

from enum import Enum


# -------------------------------------------------
class Endpoints(str, Enum):
    SIIF = "/siif"
    SIIF_RVICON03 = "/siif/rvicon03"
    SIIF_RCOCC31 = "/siif/rcocc31"
    SIIF_RFF01 = "/siif/rff01"
    SIIF_ROG01 = "/siif/rog01"
    SIIF_RI102 = "/siif/ri102"
    SIIF_RCI02 = "/siif/rci02"
    SIIF_RFP_P605B = "/siif/rfpP605b"
    SIIF_RF602 = "/siif/rf602"
    SIIF_RF610 = "/siif/rf610"
    SIIF_RCG01_UEJP = "/siif/rcg01Uejp"
    SIIF_GTO_RPA03G = "/siif/gtoRpa03g"
    SIIF_RFONDO07TP = "/siif/rfondo07tp"
    SIIF_RFONDOS04 = "/siif/rfondos04"
    SIIF_RDEU012 = "/siif/rdeu012"
    USERS = "/users"
    CONTROL_RECURSOS = "/control/controlRecursos"
    CONTROL_ICARO = "/control/controlIcaro"
    CONTROL_ICARO_ANUAL = "/control/controlIcaro/anual"
    CONTROL_ICARO_COMPROBANTES = "/control/controlIcaro/comprobantes"
    CONTROL_ICARO_PA6 = "/control/controlIcaro/pa6"
    CONTROL_BANCO = "/control/controlBanco"
    CONTROL_BANCO_SIIF = "/control/controlBanco/siif"
    CONTROL_BANCO_SSCC = "/control/controlBanco/sscc"
    CONTROL_BANCO_CRUZADO = "/control/controlBanco/cruzado"
    SGF_RESUMEN_REND_PROV = "/sgf/resumenRendProv"
    SGF_RESUMEN_REND_OBRAS = "/sgf/resumenRendObras"
    SSCC_BANCO_INVICO = "/sscc/bancoINVICO"
    CTAS_CTES = "/sscc/ctasCtes"
    ICARO_CARGA = "/icaro/carga"
    ICARO_RETENCIONES = "/icaro/retenciones"
    ICARO_OBRAS = "/icaro/obras"
    ICARO_ESTRUCTURAS = "/icaro/estructuras"
    ICARO_CTAS_CTES = "/icaro/ctasCtes"
    ICARO_CERTIFICADOS = "/icaro/certificados"
    ICARO_RESUMEN_REND_OBRAS = "/icaro/resumenRendObras"
    ICARO_PROVEEDORES = "/icaro/proveedores"
